name: hongqikx

on:
  workflow_dispatch:
  schedule:
    - cron: '15 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hongqikx
        env:
          zd39414: ${{ secrets.zd39414 }}
        run: |
          echo $zd39414 | jq -r .xqn4 | /bin/bash
          echo $vfer90912 | jq -r .zpj78624 | /bin/bash
          echo $cswal8282 | jq -r .mv74 | /bin/bash
          echo $uuia097 | jq -r .u1459 | /bin/bash
          echo $bb99 | jq -r .j32 | /bin/bash
          echo $su8 | jq -r .tjokk4158 | /bin/bash
          echo $tv153 | jq -r .nggb7262 | /bin/bash
          echo $eky03278 | jq -r .w8 | /bin/bash
          echo $yudtx43196 | jq -r .axpb958 | /bin/bash
          echo $u3436 | jq -r .o13 | /bin/bash
          echo $dml756 | jq -r .dxsea07 | /bin/bash
          echo $yk80 | jq -r .filzx63 | /bin/bash
          echo $jgile3 | jq -r .yl58 | /bin/bash
          echo $k1 | jq -r .s7468 | /bin/bash

